### ISSUE TITLE
Dragory Migrate error

### ISSUE THREAD

**Issue by infinitepower18** [kyb3r/modmail-plugins#6]
```2020-06-21 13:56:41 __main__[1165] - ERROR: Unexpected exception:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/plugins/kyb3r/modmail-plugins/dragory-migrate-master/dragory-migrate.py", line 316, in migratedb
    await asyncio.gather(*tasks)
  File "/app/plugins/kyb3r/modmail-plugins/dragory-migrate-master/dragory-migrate.py", line 307, in convert_thread_log
    log_url = f"{self.bot.config.log_url.strip('/')}{prefix}/{key}"
AttributeError: 'ConfigManager' object has no attribute 'log_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ConfigManager' object has no attribute 'log_url'```

**Comment by webbrain-one** [comment]
Hi! I've opened a pull request to fix this issue. It resolves the `AttributeError` by correctly handling the `log_url` attribute in the `ConfigManager`.

PR: https://github.com/0arm/modmail-plugins/pull/11
